- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://ftp.joelsprouse.co.uk'
    username: 'joel@joelsprouse.co.uk'
    password: '5rXTxMxst&eh6@sd'
    rootDirectory: '/'
    filePatterns: '**'
    remoteDirectory: '/upload/$(Build.BuildId)/'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false