const floorDiv = document.getElementById('floor');
const playerDiv = document.getElementById('player');

playerDiv.style.display = "flex";
playerDiv.style.alignItems = "center";
playerDiv.style.flexDirection = "column";
//playerDiv.style.height = "4vh";
//playerDiv.style.width = "4vh";
playerDiv.style.position = "absolute";
playerDiv.style.top = "50%";
playerDiv.style.left = "50%";
playerDiv.style.transform = "translate(-50%, -50%)";
playerDiv.style.zIndex = "5";
playerDiv.style.transition = "left ease-in-out 0.01s, top ease-in-out 0.01s";
var playerHead = document.createElement("div");
playerHead.classList.add("head");
playerHead.style.height = "1.1vh";
playerHead.style.width = "1.1vh";
playerHead.style.background = "gray";
playerHead.style.borderRadius = "4px 4px 0 0";
playerDiv.appendChild(playerHead);
var playerNeck = document.createElement("div");
playerNeck.classList.add("neck");
playerNeck.style.height = "0.1538461538vh";
playerNeck.style.width = "0.6vh";
playerNeck.style.background = "gray";
playerDiv.appendChild(playerNeck);
var playerTorso = document.createElement("div");
playerTorso.classList.add("torso");
playerTorso.style.height = "1.5vh";
playerTorso.style.width = "1.5vh";
playerTorso.style.background = "#ff0000";
playerDiv.appendChild(playerTorso);
var playerArms = document.createElement("div");
playerArms.classList.add("arms");
playerArms.style.position = "relative";
playerArms.style.bottom = "1.5vh";
playerArms.style.right = "0.95vh";
playerDiv.appendChild(playerArms);
var playerArmL = document.createElement("div");
playerArmL.classList.add("left");
playerArmL.classList.add("arm");
playerArmL.style.height = "1.3vh";
playerArmL.style.width = "0.45vh";
playerArmL.style.position = "absolute";
playerArmL.style.background = "#ff0000";
playerArmL.style.left = "-0.25vh";
playerArmL.style.transform = "rotate(10deg)";
playerArms.appendChild(playerArmL);
var playerArmR = document.createElement("div");
playerArmR.classList.add("right");
playerArmR.classList.add("arm");
playerArmR.style.height = "1.3vh";
playerArmR.style.width = "0.45vh";
playerArmR.style.position = "absolute";
playerArmR.style.background = "#ff0000";
playerArmR.style.left = "1.65vh";
playerArmR.style.transform = "rotate(345deg)";
playerArms.appendChild(playerArmR);
var playerLegs = document.createElement("div");
playerLegs.classList.add("legs");
playerLegs.style.position = "relative";
playerLegs.style.left = "-0.2vh";
playerLegs.style.height = "1.45vh";
playerDiv.appendChild(playerLegs);
var playerLegL = document.createElement("div");
playerLegL.classList.add("left");
playerLegL.classList.add("leg");
playerLegL.style.height = "1.45vh";
playerLegL.style.width = "0.6vh";
playerLegL.style.background = "black";
playerLegL.style.position = "absolute";
playerLegL.style.left = "-0.5vh";
playerLegs.appendChild(playerLegL);
var playerLegR = document.createElement("div");
playerLegR.classList.add("right");
playerLegR.classList.add("leg");
playerLegR.style.height = "1.45vh";
playerLegR.style.width = "0.6vh";
playerLegR.style.background = "black";
playerLegR.style.position = "absolute";
playerLegR.style.left = "0.35vh";
playerLegs.appendChild(playerLegR);